framework: mocha

preRun:
  command:
    - yarn install --frozen-lockfile
    - yarn compile

preMerge:
  pattern:
    - test/unit/node/index.js
postMerge:
  pattern:
    - test/unit/node/index.js

postRun:
  command:
    - node --version

nodeVersion: 16.14.0
version: 1.0
